UserBundle\Entity\User:
    type:  entity
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        facebookId:
            type: string
            column: facebook_id
        accessToken:
            type: string
            column: access_token
        added:
            type: datetime
            options:
                default: CURRENT_TIMESTAMP