login_failure:
    path:     /login-fail
    defaults: { _controller: UserBundle:FacebookLogin:loginFail }

login_success:
    path:     /login-success
    defaults: { _controller: UserBundle:FacebookLogin:loginSuccess }
