AppBundle\Entity\Credentials:
    type: entity
    table: credentials
    repositoryClass: AppBundle\Repository\CredentialsRepository

    id:
        id:
            type: integer
            id: true
            options:
                unsigned: true
            generator:
                strategy: AUTO
    fields:
        credential:
            type: string
        type:
            type: smallint
        lastUsed:
            type: datetime
            nullable: true
            options:
                default: null