AppBundle\Entity\Jokes:
    type: entity
    table: jokes
    repositoryClass: AppBundle\Repository\JokesRepository

    id:
        id:
            type: integer
            id: true
            options:
                unsigned: true
            generator:
                strategy: AUTO
    fields:
        joke:
            type: text
        lastUsed:
            type: datetime
            nullable: true
            options:
                default: null